export { default as Page } from './Page'
export { default as Detail } from './Detail'
export { default as EditTable } from './EditTable'
export { default as BaseInfo } from './BaseInfo'
export { default as FormItemType } from './FormItemType'
export { default as DetailContent } from './DetailContent'
export { default as CommonTable } from './CommonTable'
export { default as DetailTitle } from './DetailTitle'
export type { BaseInfoColumnsProps } from './BaseInfo'
export type { FormItemTypesType } from './FormItemType'