export { default as Page } from './Page'
export { default as Detail } from './Detail'
export { default as EditTable } from './EditTable'
export { default as EditableTable } from './EditableTable'
export { default as BaseInfo, formatData, formatDataType } from './BaseInfo'
export { default as FormItemType, PopTable, PopTableContent } from './FormItemType'
export { default as DetailContent } from './DetailContent'
export { default as CommonTable, generateRender } from './CommonTable'
export { default as CommonAliTable } from './CommonAliTable'
export { default as SearchTable } from './SearchTable'
export { default as DetailTitle } from './DetailTitle'
export { default as EditTabs } from './EditTabs'
export { default as Attachment } from './Attachment'
export { default as BatchAttachment } from './BatchAttachment'
export { default as IntgSelect, generateTreeNode } from './IntgSelect'
export { default as SupplySelect } from './SupplySelect'
export { default as OperationRecord } from './OperationRecord'
export { default as AuthButton } from './AuthButton'
export { default as UploadXLSX } from './UploadXLSX'
export { default as Workflow } from './Workflow'
export type { BaseInfoColumnsProps } from './BaseInfo'
export type { FormItemTypesType } from './FormItemType'
export type { AttachmentRef } from './Attachment'