export { default as Page } from './Page'
export { default as Detail } from './Detail'
export { default as EditTable } from './EditTable'
export { default as BaseInfo } from './BaseInfo'
export type { BaseInfoItemProps } from './BaseInfo'